#!/usr/bin/env python3
from __future__ import annotations

import argparse
import bisect
import csv
import json
import re
import shutil
import subprocess
import tarfile
import tempfile
from collections import Counter, defaultdict
from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Sequence, Tuple


RULE_LINE_RE = re.compile(r"^(alert|drop|pass|reject)\s+", re.IGNORECASE)
SID_RE = re.compile(r"\bsid\s*:\s*(\d+)", re.IGNORECASE)
MSG_RE = re.compile(r'\bmsg\s*:\s*"((?:[^"\\]|\\.)*)"', re.IGNORECASE)
CLASSTYPE_RE = re.compile(r"\bclasstype\s*:\s*([^;]+)", re.IGNORECASE)
CVE_RE = re.compile(r"\bCVE-\d{4}-\d+\b", re.IGNORECASE)
GENERIC_MSG_HINTS = (
    "trojan",
    "policy",
    "indicator",
    "misc attack",
    "scan",
    "test",
    "possible",
    "suspicious",
    "observed",
)


@dataclass(frozen=True)
class Sample:
    order_index: int
    sample_path: str
    label: str
    dataset: str
    source_pcap: str
    split_kind: str
    proto: str
    packets: int
    meta: str


@dataclass(frozen=True)
class RuleRecord:
    index: int
    source_file: str
    line_no: int
    text: str
    sid: Optional[int]
    msg: str
    classtype: str


@dataclass(frozen=True)
class Candidate:
    sid: int
    alert_count: int
    score: int
    reason: str
    msg: str
    source_file: str
    line_no: int
    classtype: str
    rule_text: str


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Build GRIDAI-style pseudo ground truth: sample -> GT rule SID -> new/repair labels."
    )
    sub = parser.add_subparsers(dest="command", required=True)

    collect_cmd = sub.add_parser(
        "collect",
        help="Replay full ET rules on attack samples and export a human-readable GT curation template.",
    )
    collect_cmd.add_argument("--manifest", default="", help="TSV manifest with sample_path,label,dataset,...")
    collect_cmd.add_argument("--pcap-dir", default="", help="Fallback: recursively collect pcap/pcapng/cap files from a directory.")
    collect_cmd.add_argument("--label", default="attack", help="Only keep this label when reading manifest. Default: attack")
    collect_cmd.add_argument("--rules-dir", default="rules", help="Rules directory to replay. Prefer an extracted full ET rules directory.")
    collect_cmd.add_argument("--rules-tar", default="", help="Optional fallback: Emerging Threats tarball path.")
    collect_cmd.add_argument("--output-dir", default="output/gridai_pseudo_gt", help="Output directory.")
    collect_cmd.add_argument("--suricata", default="/usr/bin/suricata", help="Suricata binary path.")
    collect_cmd.add_argument("--suricata-config", default="/etc/suricata/suricata.yaml", help="Suricata config path.")
    collect_cmd.add_argument("--mergecap", default="/usr/bin/mergecap", help="mergecap binary path.")
    collect_cmd.add_argument("--force", action="store_true", help="Force rerun Suricata replay and rebuild caches.")

    derive_cmd = sub.add_parser(
        "derive",
        help="Convert curated GT rule SIDs into GRIDAI-style new/repair pseudo labels.",
    )
    derive_cmd.add_argument(
        "--curation-tsv",
        default="output/gridai_pseudo_gt/sample_gt_template.tsv",
        help="Curated TSV generated by the collect step.",
    )
    derive_cmd.add_argument(
        "--output-dir",
        default="output/gridai_pseudo_gt",
        help="Output directory for derived pseudo labels.",
    )
    derive_cmd.add_argument(
        "--use-suggested-when-missing",
        action="store_true",
        help="If curated_gt_sid is empty, fall back to suggested_sid.",
    )
    return parser.parse_args()


def ensure_dir(path: Path) -> None:
    path.mkdir(parents=True, exist_ok=True)


def run(cmd: Sequence[str], *, cwd: Optional[Path] = None) -> None:
    proc = subprocess.run(
        list(cmd),
        cwd=str(cwd) if cwd else None,
        capture_output=True,
        text=True,
        check=False,
    )
    if proc.returncode != 0:
        raise RuntimeError(
            f"Command failed ({proc.returncode}): {' '.join(cmd)}\nSTDOUT:\n{proc.stdout}\nSTDERR:\n{proc.stderr}"
        )


def read_manifest(path: Path, *, label_filter: str) -> List[Sample]:
    rows: List[Sample] = []
    with path.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for idx, row in enumerate(reader):
            if label_filter and str(row.get("label") or "").strip() != label_filter:
                continue
            packets_raw = str(row.get("packets") or "").strip()
            try:
                packets = int(packets_raw) if packets_raw else 0
            except ValueError:
                packets = 0
            rows.append(
                Sample(
                    order_index=len(rows),
                    sample_path=str(row["sample_path"]).strip(),
                    label=str(row.get("label") or "").strip(),
                    dataset=str(row.get("dataset") or "").strip(),
                    source_pcap=str(row.get("source_pcap") or "").strip(),
                    split_kind=str(row.get("split_kind") or "").strip(),
                    proto=str(row.get("proto") or "").strip(),
                    packets=packets,
                    meta=str(row.get("meta") or "").strip(),
                )
            )
    if not rows:
        raise ValueError(f"No samples matched label={label_filter!r} in {path}")
    return rows


def collect_pcaps_from_dir(path: Path) -> List[Sample]:
    files = [
        p.resolve(strict=False)
        for p in sorted(path.rglob("*"))
        if p.is_file() and p.suffix.lower() in {".pcap", ".pcapng", ".cap"}
    ]
    if not files:
        raise ValueError(f"No pcap files found under {path}")
    out: List[Sample] = []
    for idx, pcap in enumerate(files):
        out.append(
            Sample(
                order_index=idx,
                sample_path=str(pcap),
                label="attack",
                dataset="unknown",
                source_pcap=pcap.name,
                split_kind="pcap-dir",
                proto="unknown",
                packets=0,
                meta="",
            )
        )
    return out


def collect_rule_records(path: Path) -> List[RuleRecord]:
    records: List[RuleRecord] = []

    def iter_rule_files(base: Path) -> Iterable[Path]:
        if base.is_file():
            yield base
            return
        for child in sorted(base.rglob("*")):
            if child.is_file() and child.suffix.lower() in {".rules", ".rule", ".txt"}:
                yield child

    root = path if path.is_dir() else path.parent
    for rule_file in iter_rule_files(path):
        rel = str(rule_file.relative_to(root))
        for line_no, line in enumerate(rule_file.read_text(encoding="utf-8", errors="ignore").splitlines(), start=1):
            rule = line.strip()
            if not rule or rule.startswith("#") or not RULE_LINE_RE.match(rule):
                continue
            sid_match = SID_RE.search(rule)
            msg_match = MSG_RE.search(rule)
            classtype_match = CLASSTYPE_RE.search(rule)
            sid = int(sid_match.group(1)) if sid_match else None
            msg = _clean_rule_string(msg_match.group(1)) if msg_match else ""
            classtype = str(classtype_match.group(1)).strip() if classtype_match else ""
            records.append(
                RuleRecord(
                    index=len(records),
                    source_file=rel,
                    line_no=line_no,
                    text=rule,
                    sid=sid,
                    msg=msg,
                    classtype=classtype,
                )
            )
    if not records:
        raise ValueError(f"No active rules found under {path}")
    return records


def _clean_rule_string(value: str) -> str:
    return value.replace(r"\"", '"').replace(r"\\", "\\").strip()


def write_rule_file(records: Sequence[RuleRecord], output_path: Path) -> None:
    ensure_dir(output_path.parent)
    with output_path.open("w", encoding="utf-8") as f:
        for record in records:
            f.write(record.text)
            f.write("\n")


def sample_packet_ends(samples: Sequence[Sample]) -> List[int]:
    ends: List[int] = []
    total = 0
    for sample in samples:
        total += sample.packets
        ends.append(total)
    return ends


def can_use_merged_replay(samples: Sequence[Sample], mergecap_path: str) -> bool:
    mergecap = Path(mergecap_path)
    if not mergecap.exists():
        return False
    if not all(sample.packets > 0 for sample in samples):
        return False
    return True


def merge_dataset_pcaps(samples: Sequence[Sample], mergecap_path: str, merged_pcap: Path, metadata_path: Path, *, force: bool) -> None:
    current_meta = {
        "sample_paths": [s.sample_path for s in samples],
        "packets": [s.packets for s in samples],
    }
    if merged_pcap.exists() and metadata_path.exists() and not force:
        try:
            existing = json.loads(metadata_path.read_text(encoding="utf-8"))
        except Exception:
            existing = None
        if existing == current_meta:
            return

    ensure_dir(merged_pcap.parent)
    if merged_pcap.exists():
        merged_pcap.unlink()
    cmd = [mergecap_path, "-a", "-w", str(merged_pcap)]
    cmd.extend(sample.sample_path for sample in samples)
    run(cmd)
    metadata_path.write_text(json.dumps(current_meta, ensure_ascii=False, indent=2), encoding="utf-8")


def replay_full_rules_merged(
    *,
    suricata_path: str,
    suricata_config: str,
    merged_pcap: Path,
    rule_file: Path,
    samples: Sequence[Sample],
    cache_path: Path,
    force: bool,
) -> Dict[str, List[dict]]:
    if cache_path.exists() and not force:
        raw = json.loads(cache_path.read_text(encoding="utf-8"))
        return {str(k): list(v or []) for k, v in raw.items()}

    ends = sample_packet_ends(samples)
    results: Dict[str, List[dict]] = {sample.sample_path: [] for sample in samples}

    with tempfile.TemporaryDirectory(prefix="gridai-gt-merged-") as log_dir:
        proc = subprocess.run(
            [
                suricata_path,
                "-r",
                str(merged_pcap),
                "-S",
                str(rule_file),
                "-c",
                suricata_config,
                "-l",
                log_dir,
                "--runmode",
                "single",
            ],
            capture_output=True,
            text=True,
            check=False,
        )
        if proc.returncode != 0:
            raise RuntimeError(
                f"Suricata replay failed for {rule_file}\nSTDOUT:\n{proc.stdout}\nSTDERR:\n{proc.stderr}"
            )
        eve_path = Path(log_dir) / "eve.json"
        if not eve_path.exists():
            raise FileNotFoundError(f"Expected eve.json not found in {log_dir}")

        with eve_path.open("r", encoding="utf-8", errors="ignore") as f:
            for line in f:
                line = line.strip()
                if not line:
                    continue
                try:
                    event = json.loads(line)
                except json.JSONDecodeError:
                    continue
                if event.get("event_type") != "alert":
                    continue
                pcap_cnt = event.get("pcap_cnt")
                alert = event.get("alert") or {}
                sid = alert.get("signature_id")
                if not isinstance(pcap_cnt, int) or not isinstance(sid, int):
                    continue
                sample_idx = bisect.bisect_left(ends, pcap_cnt)
                if sample_idx >= len(samples):
                    raise IndexError(f"pcap_cnt {pcap_cnt} out of range for merged packet boundaries")
                sample_path = samples[sample_idx].sample_path
                results[sample_path].append(
                    {
                        "pcap_cnt": pcap_cnt,
                        "sid": sid,
                        "signature": str(alert.get("signature") or "").strip(),
                        "category": str(alert.get("category") or "").strip(),
                        "severity": int(alert.get("severity") or 0) if str(alert.get("severity") or "").isdigit() else 0,
                    }
                )

    cache_path.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8")
    return results


def replay_full_rules_per_sample(
    *,
    suricata_path: str,
    suricata_config: str,
    rule_file: Path,
    samples: Sequence[Sample],
    cache_path: Path,
    force: bool,
) -> Dict[str, List[dict]]:
    if cache_path.exists() and not force:
        raw = json.loads(cache_path.read_text(encoding="utf-8"))
        return {str(k): list(v or []) for k, v in raw.items()}

    ensure_dir(cache_path.parent)
    results: Dict[str, List[dict]] = {}
    for index, sample in enumerate(samples, start=1):
        sample_path = sample.sample_path
        with tempfile.TemporaryDirectory(prefix="gridai-gt-sample-") as log_dir:
            proc = subprocess.run(
                [
                    suricata_path,
                    "-r",
                    sample_path,
                    "-S",
                    str(rule_file),
                    "-c",
                    suricata_config,
                    "-l",
                    log_dir,
                    "--runmode",
                    "single",
                ],
                capture_output=True,
                text=True,
                check=False,
            )
            if proc.returncode != 0:
                raise RuntimeError(
                    f"Suricata replay failed for sample {sample_path}\nSTDOUT:\n{proc.stdout}\nSTDERR:\n{proc.stderr}"
                )
            alerts: List[dict] = []
            eve_path = Path(log_dir) / "eve.json"
            if eve_path.exists():
                with eve_path.open("r", encoding="utf-8", errors="ignore") as f:
                    for line in f:
                        line = line.strip()
                        if not line:
                            continue
                        try:
                            event = json.loads(line)
                        except json.JSONDecodeError:
                            continue
                        if event.get("event_type") != "alert":
                            continue
                        alert = event.get("alert") or {}
                        sid = alert.get("signature_id")
                        if not isinstance(sid, int):
                            continue
                        alerts.append(
                            {
                                "pcap_cnt": int(event.get("pcap_cnt") or 0),
                                "sid": sid,
                                "signature": str(alert.get("signature") or "").strip(),
                                "category": str(alert.get("category") or "").strip(),
                                "severity": int(alert.get("severity") or 0) if str(alert.get("severity") or "").isdigit() else 0,
                            }
                        )
            results[sample_path] = alerts
        if index % 25 == 0 or index == len(samples):
            print(f"[collect] replayed {index}/{len(samples)} samples")

    cache_path.write_text(json.dumps(results, ensure_ascii=False, indent=2), encoding="utf-8")
    return results


def summarize_candidates(
    *,
    sample: Sample,
    alerts: Sequence[dict],
    rule_by_sid: Dict[int, RuleRecord],
) -> List[Candidate]:
    sid_counter = Counter()
    for alert in alerts:
        sid = alert.get("sid")
        if isinstance(sid, int):
            sid_counter[sid] += 1

    sample_text = " ".join(
        part.lower()
        for part in [
            Path(sample.sample_path).stem,
            sample.dataset,
            sample.source_pcap,
            sample.split_kind,
            sample.proto,
            sample.meta,
        ]
        if str(part).strip()
    )
    sample_terms = {token for token in re.findall(r"[a-z0-9]+", sample_text) if len(token) >= 3}

    candidates: List[Candidate] = []
    for sid, count in sid_counter.items():
        record = rule_by_sid.get(sid)
        if record is None:
            continue
        score = count * 10
        reasons: List[str] = [f"alert_count={count}"]

        msg_lower = record.msg.lower()
        if record.source_file.startswith(("emerging-exploit", "emerging-web", "emerging-sql", "emerging-malware")):
            score += 8
            reasons.append(f"source_file={record.source_file}")
        if CVE_RE.search(record.msg):
            score += 15
            reasons.append("msg_has_cve")
        if record.classtype:
            score += 3
            reasons.append(f"classtype={record.classtype}")
        if any(hint in msg_lower for hint in GENERIC_MSG_HINTS):
            score -= 8
            reasons.append("generic_msg_penalty")

        rule_text_lower = record.text.lower()
        overlap = sorted(term for term in sample_terms if term in msg_lower or term in rule_text_lower)
        if overlap:
            score += min(20, len(overlap) * 2)
            reasons.append(f"term_overlap={','.join(overlap[:8])}")

        candidates.append(
            Candidate(
                sid=sid,
                alert_count=count,
                score=score,
                reason=";".join(reasons),
                msg=record.msg,
                source_file=record.source_file,
                line_no=record.line_no,
                classtype=record.classtype,
                rule_text=record.text,
            )
        )

    candidates.sort(key=lambda item: (-item.score, -item.alert_count, item.source_file, item.line_no, item.sid))
    return candidates


def write_collect_outputs(
    *,
    output_dir: Path,
    samples: Sequence[Sample],
    alert_map: Dict[str, List[dict]],
    candidate_map: Dict[str, List[Candidate]],
) -> None:
    ensure_dir(output_dir)
    alerts_jsonl = output_dir / "sample_alerts.jsonl"
    candidates_tsv = output_dir / "sample_sid_candidates.tsv"
    template_tsv = output_dir / "sample_gt_template.tsv"
    sid_groups_tsv = output_dir / "sid_group_summary.tsv"
    summary_json = output_dir / "summary.json"

    sid_groups: Dict[int, List[Sample]] = defaultdict(list)
    matched_samples = 0

    with alerts_jsonl.open("w", encoding="utf-8") as alerts_f, candidates_tsv.open("w", encoding="utf-8", newline="") as cand_f, template_tsv.open("w", encoding="utf-8", newline="") as templ_f:
        cand_writer = csv.DictWriter(
            cand_f,
            fieldnames=[
                "order_index",
                "sample_path",
                "dataset",
                "source_pcap",
                "sid",
                "alert_count",
                "score",
                "msg",
                "source_file",
                "line_no",
                "classtype",
                "reason",
                "rule_text",
            ],
            delimiter="\t",
        )
        templ_writer = csv.DictWriter(
            templ_f,
            fieldnames=[
                "order_index",
                "sample_path",
                "label",
                "dataset",
                "source_pcap",
                "split_kind",
                "proto",
                "packets",
                "meta",
                "matched_alert_count",
                "candidate_sid_count",
                "suggested_sid",
                "suggested_msg",
                "suggested_source_file",
                "suggested_score",
                "all_candidate_sids",
                "all_candidate_msgs",
                "curated_gt_sid",
                "curation_status",
                "curation_notes",
            ],
            delimiter="\t",
        )
        cand_writer.writeheader()
        templ_writer.writeheader()

        for sample in samples:
            alerts = list(alert_map.get(sample.sample_path) or [])
            candidates = list(candidate_map.get(sample.sample_path) or [])
            suggested = candidates[0] if candidates else None
            if suggested is not None:
                sid_groups[suggested.sid].append(sample)
            if alerts:
                matched_samples += 1

            alerts_f.write(
                json.dumps(
                    {
                        "order_index": sample.order_index,
                        "sample_path": sample.sample_path,
                        "dataset": sample.dataset,
                        "source_pcap": sample.source_pcap,
                        "matched_alert_count": len(alerts),
                        "alerts": alerts,
                    },
                    ensure_ascii=False,
                )
            )
            alerts_f.write("\n")

            for candidate in candidates:
                cand_writer.writerow(
                    {
                        "order_index": sample.order_index,
                        "sample_path": sample.sample_path,
                        "dataset": sample.dataset,
                        "source_pcap": sample.source_pcap,
                        "sid": candidate.sid,
                        "alert_count": candidate.alert_count,
                        "score": candidate.score,
                        "msg": candidate.msg,
                        "source_file": candidate.source_file,
                        "line_no": candidate.line_no,
                        "classtype": candidate.classtype,
                        "reason": candidate.reason,
                        "rule_text": candidate.rule_text,
                    }
                )

            templ_writer.writerow(
                {
                    "order_index": sample.order_index,
                    "sample_path": sample.sample_path,
                    "label": sample.label,
                    "dataset": sample.dataset,
                    "source_pcap": sample.source_pcap,
                    "split_kind": sample.split_kind,
                    "proto": sample.proto,
                    "packets": sample.packets,
                    "meta": sample.meta,
                    "matched_alert_count": len(alerts),
                    "candidate_sid_count": len(candidates),
                    "suggested_sid": (suggested.sid if suggested else ""),
                    "suggested_msg": (suggested.msg if suggested else ""),
                    "suggested_source_file": (suggested.source_file if suggested else ""),
                    "suggested_score": (suggested.score if suggested else ""),
                    "all_candidate_sids": ",".join(str(item.sid) for item in candidates),
                    "all_candidate_msgs": " || ".join(item.msg for item in candidates[:8]),
                    "curated_gt_sid": "",
                    "curation_status": "",
                    "curation_notes": "",
                }
            )

    with sid_groups_tsv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "sid",
                "sample_count",
                "first_order_index",
                "first_sample_path",
                "datasets",
            ],
            delimiter="\t",
        )
        writer.writeheader()
        for sid, grouped_samples in sorted(sid_groups.items(), key=lambda item: (-len(item[1]), item[0])):
            ordered = sorted(grouped_samples, key=lambda sample: sample.order_index)
            writer.writerow(
                {
                    "sid": sid,
                    "sample_count": len(ordered),
                    "first_order_index": ordered[0].order_index,
                    "first_sample_path": ordered[0].sample_path,
                    "datasets": ",".join(sorted({sample.dataset for sample in ordered if sample.dataset})),
                }
            )

    summary = {
        "sample_count": len(samples),
        "matched_sample_count": matched_samples,
        "unmatched_sample_count": len(samples) - matched_samples,
        "suggested_sid_group_count": len(sid_groups),
        "outputs": {
            "sample_alerts_jsonl": str(alerts_jsonl.resolve()),
            "sample_sid_candidates_tsv": str(candidates_tsv.resolve()),
            "sample_gt_template_tsv": str(template_tsv.resolve()),
            "sid_group_summary_tsv": str(sid_groups_tsv.resolve()),
        },
    }
    summary_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")


def derive_pseudo_labels(
    *,
    curation_tsv: Path,
    output_dir: Path,
    use_suggested_when_missing: bool,
) -> None:
    ensure_dir(output_dir)
    rows: List[dict] = []
    with curation_tsv.open("r", encoding="utf-8", newline="") as f:
        reader = csv.DictReader(f, delimiter="\t")
        for row in reader:
            rows.append(dict(row))

    rows.sort(key=lambda row: int(str(row.get("order_index") or "0")))

    seen_sid: set[int] = set()
    derived_rows: List[dict] = []
    group_rows: List[dict] = []
    grouped_paths: Dict[int, List[str]] = defaultdict(list)

    for row in rows:
        raw_status = str(row.get("curation_status") or "").strip().lower()
        if raw_status in {"skip", "ambiguous", "exclude", "unmatched"}:
            continue

        chosen_sid_raw = str(row.get("curated_gt_sid") or "").strip()
        if not chosen_sid_raw and use_suggested_when_missing:
            chosen_sid_raw = str(row.get("suggested_sid") or "").strip()
        if not chosen_sid_raw:
            continue
        try:
            chosen_sid = int(chosen_sid_raw)
        except ValueError:
            continue

        expected_action = "new-rule-generation" if chosen_sid not in seen_sid else "rule-repair"
        repair_target_sid = "" if expected_action == "new-rule-generation" else str(chosen_sid)
        seen_sid.add(chosen_sid)
        grouped_paths[chosen_sid].append(str(row.get("sample_path") or ""))

        derived_rows.append(
            {
                "order_index": row.get("order_index") or "",
                "sample_path": row.get("sample_path") or "",
                "dataset": row.get("dataset") or "",
                "source_pcap": row.get("source_pcap") or "",
                "gt_rule_sid": chosen_sid,
                "expected_action": expected_action,
                "repair_target_sid": repair_target_sid,
                "curation_status": row.get("curation_status") or "",
                "curation_notes": row.get("curation_notes") or "",
            }
        )

    for sid, sample_paths in sorted(grouped_paths.items()):
        group_rows.append(
            {
                "gt_rule_sid": sid,
                "sample_count": len(sample_paths),
                "first_sample_path": sample_paths[0],
            }
        )

    pseudo_tsv = output_dir / "gridai_pseudo_labels.tsv"
    pseudo_jsonl = output_dir / "gridai_pseudo_labels.jsonl"
    groups_tsv = output_dir / "gridai_gt_rule_groups.tsv"
    summary_json = output_dir / "gridai_pseudo_labels_summary.json"

    with pseudo_tsv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=[
                "order_index",
                "sample_path",
                "dataset",
                "source_pcap",
                "gt_rule_sid",
                "expected_action",
                "repair_target_sid",
                "curation_status",
                "curation_notes",
            ],
            delimiter="\t",
        )
        writer.writeheader()
        for row in derived_rows:
            writer.writerow(row)

    with pseudo_jsonl.open("w", encoding="utf-8") as f:
        for row in derived_rows:
            f.write(json.dumps(row, ensure_ascii=False))
            f.write("\n")

    with groups_tsv.open("w", encoding="utf-8", newline="") as f:
        writer = csv.DictWriter(
            f,
            fieldnames=["gt_rule_sid", "sample_count", "first_sample_path"],
            delimiter="\t",
        )
        writer.writeheader()
        for row in group_rows:
            writer.writerow(row)

    summary = {
        "total_labeled_samples": len(derived_rows),
        "new_rule_generation_count": sum(1 for row in derived_rows if row["expected_action"] == "new-rule-generation"),
        "rule_repair_count": sum(1 for row in derived_rows if row["expected_action"] == "rule-repair"),
        "gt_rule_sid_count": len(group_rows),
        "outputs": {
            "pseudo_labels_tsv": str(pseudo_tsv.resolve()),
            "pseudo_labels_jsonl": str(pseudo_jsonl.resolve()),
            "gt_rule_groups_tsv": str(groups_tsv.resolve()),
        },
    }
    summary_json.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")


def _resolve_rules_dir(*, rules_dir: str, rules_tar: str, output_dir: Path) -> Tuple[Path, Optional[tempfile.TemporaryDirectory[str]]]:
    if rules_dir:
        path = Path(rules_dir).resolve()
        if not path.exists():
            raise FileNotFoundError(f"Rules directory not found: {path}")
        return path, None

    tar_path = Path(rules_tar).resolve()
    if not tar_path.exists():
        raise FileNotFoundError(f"Rules tarball not found: {tar_path}")
    temp_dir = tempfile.TemporaryDirectory(prefix="gridai-full-rules-")
    td_path = Path(temp_dir.name)
    with tarfile.open(tar_path, "r:gz") as tf:
        tf.extractall(td_path)
    rules_root = td_path / "rules"
    if not rules_root.exists():
        raise FileNotFoundError(f"Extracted rules directory not found in tarball: {tar_path}")
    return rules_root, temp_dir


def do_collect(args: argparse.Namespace) -> None:
    if bool(args.manifest) == bool(args.pcap_dir):
        raise ValueError("Exactly one of --manifest or --pcap-dir must be provided.")

    output_dir = Path(args.output_dir).resolve()
    ensure_dir(output_dir)

    if args.manifest:
        samples = read_manifest(Path(args.manifest).resolve(), label_filter=args.label)
    else:
        samples = collect_pcaps_from_dir(Path(args.pcap_dir).resolve())

    rules_root, temp_rules_dir = _resolve_rules_dir(rules_dir=args.rules_dir, rules_tar=args.rules_tar, output_dir=output_dir)
    try:
        rules = collect_rule_records(rules_root)
        rule_by_sid = {record.sid: record for record in rules if record.sid is not None}
        full_rule_file = output_dir / "full.rules"
        write_rule_file(rules, full_rule_file)

        if can_use_merged_replay(samples, args.mergecap):
            merged_pcap = output_dir / "attack_samples_merged.pcap"
            merged_meta = output_dir / "attack_samples_merged.json"
            merge_dataset_pcaps(samples, args.mergecap, merged_pcap, merged_meta, force=args.force)
            alert_map = replay_full_rules_merged(
                suricata_path=args.suricata,
                suricata_config=args.suricata_config,
                merged_pcap=merged_pcap,
                rule_file=full_rule_file,
                samples=samples,
                cache_path=output_dir / "full_rules_alert_map.json",
                force=args.force,
            )
            replay_mode = "merged"
        else:
            alert_map = replay_full_rules_per_sample(
                suricata_path=args.suricata,
                suricata_config=args.suricata_config,
                rule_file=full_rule_file,
                samples=samples,
                cache_path=output_dir / "full_rules_alert_map.json",
                force=args.force,
            )
            replay_mode = "per-sample"

        candidate_map: Dict[str, List[Candidate]] = {}
        for sample in samples:
            candidate_map[sample.sample_path] = summarize_candidates(
                sample=sample,
                alerts=alert_map.get(sample.sample_path) or [],
                rule_by_sid=rule_by_sid,
            )

        write_collect_outputs(
            output_dir=output_dir,
            samples=samples,
            alert_map=alert_map,
            candidate_map=candidate_map,
        )

        summary_path = output_dir / "summary.json"
        summary = json.loads(summary_path.read_text(encoding="utf-8"))
        summary["replay_mode"] = replay_mode
        summary["rule_count"] = len(rules)
        summary["unique_rule_sid_count"] = len(rule_by_sid)
        summary_path.write_text(json.dumps(summary, ensure_ascii=False, indent=2), encoding="utf-8")

        print(json.dumps(summary, ensure_ascii=False, indent=2))
    finally:
        if temp_rules_dir is not None:
            temp_rules_dir.cleanup()


def do_derive(args: argparse.Namespace) -> None:
    derive_pseudo_labels(
        curation_tsv=Path(args.curation_tsv).resolve(),
        output_dir=Path(args.output_dir).resolve(),
        use_suggested_when_missing=bool(args.use_suggested_when_missing),
    )
    summary = json.loads((Path(args.output_dir).resolve() / "gridai_pseudo_labels_summary.json").read_text(encoding="utf-8"))
    print(json.dumps(summary, ensure_ascii=False, indent=2))


def main() -> None:
    args = parse_args()
    if args.command == "collect":
        do_collect(args)
    elif args.command == "derive":
        do_derive(args)
    else:
        raise ValueError(f"Unsupported command: {args.command}")


if __name__ == "__main__":
    main()
